locale:         'ru'
permalink:      /:title/

safe:           false
# lsi:            BOOL
markdown:       kramdown
exclude:        ['theme']

site_mail:      'matmuchrapna@gmail.com'



#mirror_url:     'http://vstarkov.com'
#mirror_title:   'In english'


i18n_menu:
  'ru': 'Меню'
  'en': 'Menu'
# _includes/share.html
i18n_cta_share:
  'ru': 'Расскажите друзьям про эту статью в'
  'en': 'Share this article to your friends from'
i18n_cta_share_tw:
  'en': 'Twitter'
  'ru': 'Twitter'
i18n_cta_share_and:
  'en': ' and '
  'ru': ' и '
i18n_cta_share_fb:
  'en': 'Facebook'
  'ru': 'Facebook'
i18n_cta_share_gp:
  'en': 'Google Plus'
  'ru': 'Google Plus'
i18n_twitter:
  'en': 'matmuchrapna_en'
  'ru': 'matmuchrapna'


# _includes/follow.html
i18n_cta_follow:
  'en': 'Follow me on twitter'
  'ru': 'Подписывайтесь на меня в твиттере'


# _includes/gauges.html
i18n_data-site-id:
  'en': '51bc4a78108d7b45ec000005'
  'ru': '51aeac4ff5a1f575d5000078'

# _includes/interactions.html
i18n_repo:
  'en': 'vstarkov.com'
  'ru': 'vstarkov.ru'
i18n_start_discussion:
  'en': 'Start discussion'
  'ru': 'Начать обсуждение'
i18n_join_discussion:
  'en': 'Join discussion'
  'ru': 'Присоединиться к обсуждению'


# _includes/head.html
i18n_rss_url:
  'en': 'http://feeds.feedburner.com/vstarkovcom'
  'ru': 'http://feeds.feedburner.com/vstarkovru'
i18n_site_name_short:
  'en': 'Vladimir Starkov'
  'ru': 'Владимир Старков'
i18n_site_name:
  'en': 'Vladimir Starkov; professional blog'
  'ru': 'Владимир Старков; технический блог'
i18n_site_url:
  'en': 'http://vstarkov.com'
  'ru': 'http://vstarkov.ru'


# _includes/menu.html
i18n_blog:
  'en': 'Blog'
  'ru': 'Блог'
i18n_subscribe:
  'en': 'Subscribe'
  'ru': 'Подписаться'
i18n_about:
  'en': 'About'
  'ru': 'Обо мне'


# _includes/related.html
i18n_related_articles:
  'en': 'Related articles: '
  'ru': 'Похожие статьи: '


# _includes/timeline.html
i18n_all_articles:
  'en': 'All articles'
  'ru': 'Все статьи'
i18n_january:
  'en': 'january'
  'ru': 'январь'
i18n_januaryGEN:
  'en': 'january'
  'ru': 'января'
i18n_february:
  'en': 'february'
  'ru': 'февраль'
i18n_februaryGEN:
  'en': 'february'
  'ru': 'февраля'
i18n_march:
  'en': 'march'
  'ru': 'март'
i18n_marchGEN:
  'en': 'march'
  'ru': 'марта'
i18n_april:
  'en': 'april'
  'ru': 'апрель'
i18n_aprilGEN:
  'en': 'april'
  'ru': 'апреля'
i18n_may:
  'en': 'may'
  'ru': 'май'
i18n_mayGEN:
  'en': 'may'
  'ru': 'мая'
i18n_june:
  'en': 'june'
  'ru': 'июнь'
i18n_juneGEN:
  'en': 'june'
  'ru': 'июня'
i18n_july:
  'en': 'july'
  'ru': 'июль'
i18n_julyGEN:
  'en': 'july'
  'ru': 'июля'
i18n_august:
  'en': 'august'
  'ru': 'август'
i18n_augustGEN:
  'en': 'august'
  'ru': 'августа'
i18n_september:
  'en': 'september'
  'ru': 'сентябрь'
i18n_septemberGEN:
  'en': 'september'
  'ru': 'сентября'
i18n_october:
  'en': 'october'
  'ru': 'октябрь'
i18n_octoberGEN:
  'en': 'october'
  'ru': 'октября'
i18n_november:
  'en': 'november'
  'ru': 'ноябрь'
i18n_novemberGEN:
  'en': 'november'
  'ru': 'ноября'
i18n_december:
  'en': 'december'
  'ru': 'декабрь'
i18n_decemberGEN:
  'en': 'december'
  'ru': 'декабря'
