safe:           false
permalink:      /:title/
lsi:            BOOL

markdown:       kramdown

site_url:       'http://vstarkov.ru'
site_rss:       'http://feeds.feedburner.com/vstarkov/jETN'
site_mail:      'matmuchrapna@gmail.com'
site_name:      'Владимир Старков'
site_title:     'Владимир Старков; технический блог'

site_twitter:   'matmuchrapna'

mirror_url:     'http://vstarkov.com'
mirror_title:   'In english'

i18n_lang_code: 'ru'
i18n_about:     'Обо мне'
i18n_rss:       'РСС'
i18n_close:     'Закрыть'
i18n_related:   'Похожие статьи'


i18n_cta_share:     'Расскажите друзьям про эту статью в'
i18n_cta_share_and: 'и'
i18n_cta_share_tw:  'Twitter'
i18n_cta_share_fb:  'Facebook'
i18n_cta_share_gp:  'Google Plus'

i18n_january:   'Январь'
i18n_february:  'Февраль'
i18n_march:     'Март'
i18n_april:     'Апрель'
i18n_may:       'Май'
i18n_june:      'Июнь'
i18n_july:      'Июль'
i18n_august:    'Август'
i18n_september: 'Сентябрь'
i18n_october:   'Октябрь'
i18n_november:  'Ноябрь'
i18n_december:  'Декабрь'

# i18n_january:   'Январь'
# i18n_february:  'Февраль'
# i18n_march:     'Март'
# i18n_april:     'Апрель'
# i18n_may:       'Май'
# i18n_june:      'Июнь'
# i18n_july:      'Июль'
# i18n_august:    'Август'
# i18n_september: 'Сентябрь'
# i18n_october:   'Октябрь'
# i18n_november:  'Ноябрь'
# i18n_december:  'Декабрь'